GET http://localhost:3001/info

### 

GET  http://localhost:3001/api/persons


###
DELETE  http://localhost:3001/api/persons/1


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
"name": "njk",
"phone": "22333"
}

###
DELETE http://localhost:3001/api/persons/4fe83264-6ae1-4172-ae1d-1d4cfa24a633


###
PATCH http://localhost:3001/api/persons/3becc823-3ca8-4392-a2d4-e475d23c82ec
Content-Type: text/plain

0390-9882313




